// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResearchHub.Data;

#nullable disable

namespace ResearchHub.Migrations
{
    [DbContext(typeof(ResearchHubContext))]
    [Migration("20260313170750_AddVariablePrecision")]
    partial class AddVariablePrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResearchHub.Models.Analisis", b =>
                {
                    b.Property<int>("IdAnalisis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnalisis"));

                    b.Property<string>("Conclusiones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdResultado")
                        .HasColumnType("int");

                    b.Property<string>("Metodo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdAnalisis");

                    b.HasIndex("IdResultado");

                    b.ToTable("Analisis");
                });

            modelBuilder.Entity("ResearchHub.Models.Colaborador", b =>
                {
                    b.Property<int>("IdColaborador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdColaborador"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdColaborador");

                    b.HasIndex("IdProyecto");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("ResearchHub.Models.Cronograma", b =>
                {
                    b.Property<int>("IdCronograma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCronograma"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<string>("NombreFase")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdCronograma");

                    b.HasIndex("IdProyecto");

                    b.ToTable("Cronogramas");
                });

            modelBuilder.Entity("ResearchHub.Models.EquipoLaboratorio", b =>
                {
                    b.Property<int>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipo"));

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaAdquisicion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdLaboratorio")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdEquipo");

                    b.HasIndex("IdLaboratorio");

                    b.ToTable("EquiposLaboratorio");
                });

            modelBuilder.Entity("ResearchHub.Models.Experimento", b =>
                {
                    b.Property<int>("IdExperimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExperimento"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdLaboratorio")
                        .HasColumnType("int");

                    b.Property<int>("IdProtocolo")
                        .HasColumnType("int");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdExperimento");

                    b.HasIndex("IdLaboratorio");

                    b.HasIndex("IdProtocolo");

                    b.HasIndex("IdProyecto");

                    b.ToTable("Experimentos");
                });

            modelBuilder.Entity("ResearchHub.Models.Institucion", b =>
                {
                    b.Property<int>("IdInstitucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInstitucion"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdInstitucion");

                    b.ToTable("Instituciones");
                });

            modelBuilder.Entity("ResearchHub.Models.Investigador", b =>
                {
                    b.Property<int>("IdInvestigador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInvestigador"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdInstitucion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Orcid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdInvestigador");

                    b.HasIndex("IdInstitucion");

                    b.ToTable("Investigadores");
                });

            modelBuilder.Entity("ResearchHub.Models.Laboratorio", b =>
                {
                    b.Property<int>("IdLaboratorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLaboratorio"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Responsable")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdLaboratorio");

                    b.ToTable("Laboratorios");
                });

            modelBuilder.Entity("ResearchHub.Models.LineaInvestigacion", b =>
                {
                    b.Property<int>("IdLinea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLinea"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdLinea");

                    b.ToTable("LineasInvestigacion");
                });

            modelBuilder.Entity("ResearchHub.Models.Muestra", b =>
                {
                    b.Property<int>("IdMuestra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMuestra"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Condicion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("FechaRecoleccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<string>("Origen")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdMuestra");

                    b.HasIndex("IdProyecto");

                    b.ToTable("Muestras");
                });

            modelBuilder.Entity("ResearchHub.Models.Protocolo", b =>
                {
                    b.Property<int>("IdProtocolo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProtocolo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdProtocolo");

                    b.ToTable("Protocolos");
                });

            modelBuilder.Entity("ResearchHub.Models.Proyecto", b =>
                {
                    b.Property<int>("IdProyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProyecto"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdInstitucion")
                        .HasColumnType("int");

                    b.Property<int>("IdInvestigadorPrincipal")
                        .HasColumnType("int");

                    b.Property<int>("IdLinea")
                        .HasColumnType("int");

                    b.Property<string>("ObjetivoGeneral")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdProyecto");

                    b.HasIndex("IdInstitucion");

                    b.HasIndex("IdInvestigadorPrincipal");

                    b.HasIndex("IdLinea");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("ResearchHub.Models.Publicacion", b =>
                {
                    b.Property<int>("IdPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPublicacion"));

                    b.Property<string>("DOI")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<string>("Resumen")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Revista")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdPublicacion");

                    b.HasIndex("IdProyecto");

                    b.ToTable("Publicaciones");
                });

            modelBuilder.Entity("ResearchHub.Models.RepositorioDatos", b =>
                {
                    b.Property<int>("IdRepositorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRepositorio"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdRepositorio");

                    b.HasIndex("IdProyecto");

                    b.ToTable("RepositoriosDatos");
                });

            modelBuilder.Entity("ResearchHub.Models.Resultado", b =>
                {
                    b.Property<int>("IdResultado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResultado"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdExperimento")
                        .HasColumnType("int");

                    b.Property<int>("IdVariable")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Valor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdResultado");

                    b.HasIndex("IdExperimento");

                    b.HasIndex("IdVariable");

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("ResearchHub.Models.Validacion", b =>
                {
                    b.Property<int>("IdValidacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdValidacion"));

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAnalisis")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Resultado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Validador")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdValidacion");

                    b.HasIndex("IdAnalisis");

                    b.ToTable("Validaciones");
                });

            modelBuilder.Entity("ResearchHub.Models.Variable", b =>
                {
                    b.Property<int>("IdVariable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVariable"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("RangoMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RangoMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unidad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdVariable");

                    b.ToTable("Variables");
                });

            modelBuilder.Entity("ResearchHub.Models.Analisis", b =>
                {
                    b.HasOne("ResearchHub.Models.Resultado", "Resultado")
                        .WithMany("Analisis")
                        .HasForeignKey("IdResultado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("ResearchHub.Models.Colaborador", b =>
                {
                    b.HasOne("ResearchHub.Models.Proyecto", "Proyecto")
                        .WithMany("Colaboradores")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("ResearchHub.Models.Cronograma", b =>
                {
                    b.HasOne("ResearchHub.Models.Proyecto", "Proyecto")
                        .WithMany("Cronogramas")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("ResearchHub.Models.EquipoLaboratorio", b =>
                {
                    b.HasOne("ResearchHub.Models.Laboratorio", "Laboratorio")
                        .WithMany("Equipos")
                        .HasForeignKey("IdLaboratorio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laboratorio");
                });

            modelBuilder.Entity("ResearchHub.Models.Experimento", b =>
                {
                    b.HasOne("ResearchHub.Models.Laboratorio", "Laboratorio")
                        .WithMany("Experimentos")
                        .HasForeignKey("IdLaboratorio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResearchHub.Models.Protocolo", "Protocolo")
                        .WithMany("Experimentos")
                        .HasForeignKey("IdProtocolo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResearchHub.Models.Proyecto", "Proyecto")
                        .WithMany("Experimentos")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laboratorio");

                    b.Navigation("Protocolo");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("ResearchHub.Models.Investigador", b =>
                {
                    b.HasOne("ResearchHub.Models.Institucion", "Institucion")
                        .WithMany("Investigadores")
                        .HasForeignKey("IdInstitucion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institucion");
                });

            modelBuilder.Entity("ResearchHub.Models.Muestra", b =>
                {
                    b.HasOne("ResearchHub.Models.Proyecto", "Proyecto")
                        .WithMany("Muestras")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("ResearchHub.Models.Proyecto", b =>
                {
                    b.HasOne("ResearchHub.Models.Institucion", "Institucion")
                        .WithMany("Proyectos")
                        .HasForeignKey("IdInstitucion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResearchHub.Models.Investigador", "InvestigadorPrincipal")
                        .WithMany("ProyectosPrincipales")
                        .HasForeignKey("IdInvestigadorPrincipal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResearchHub.Models.LineaInvestigacion", "LineaInvestigacion")
                        .WithMany("Proyectos")
                        .HasForeignKey("IdLinea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institucion");

                    b.Navigation("InvestigadorPrincipal");

                    b.Navigation("LineaInvestigacion");
                });

            modelBuilder.Entity("ResearchHub.Models.Publicacion", b =>
                {
                    b.HasOne("ResearchHub.Models.Proyecto", "Proyecto")
                        .WithMany("Publicaciones")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("ResearchHub.Models.RepositorioDatos", b =>
                {
                    b.HasOne("ResearchHub.Models.Proyecto", "Proyecto")
                        .WithMany("Repositorios")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("ResearchHub.Models.Resultado", b =>
                {
                    b.HasOne("ResearchHub.Models.Experimento", "Experimento")
                        .WithMany("Resultados")
                        .HasForeignKey("IdExperimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResearchHub.Models.Variable", "Variable")
                        .WithMany("Resultados")
                        .HasForeignKey("IdVariable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Experimento");

                    b.Navigation("Variable");
                });

            modelBuilder.Entity("ResearchHub.Models.Validacion", b =>
                {
                    b.HasOne("ResearchHub.Models.Analisis", "Analisis")
                        .WithMany("Validaciones")
                        .HasForeignKey("IdAnalisis")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analisis");
                });

            modelBuilder.Entity("ResearchHub.Models.Analisis", b =>
                {
                    b.Navigation("Validaciones");
                });

            modelBuilder.Entity("ResearchHub.Models.Experimento", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("ResearchHub.Models.Institucion", b =>
                {
                    b.Navigation("Investigadores");

                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("ResearchHub.Models.Investigador", b =>
                {
                    b.Navigation("ProyectosPrincipales");
                });

            modelBuilder.Entity("ResearchHub.Models.Laboratorio", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Experimentos");
                });

            modelBuilder.Entity("ResearchHub.Models.LineaInvestigacion", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("ResearchHub.Models.Protocolo", b =>
                {
                    b.Navigation("Experimentos");
                });

            modelBuilder.Entity("ResearchHub.Models.Proyecto", b =>
                {
                    b.Navigation("Colaboradores");

                    b.Navigation("Cronogramas");

                    b.Navigation("Experimentos");

                    b.Navigation("Muestras");

                    b.Navigation("Publicaciones");

                    b.Navigation("Repositorios");
                });

            modelBuilder.Entity("ResearchHub.Models.Resultado", b =>
                {
                    b.Navigation("Analisis");
                });

            modelBuilder.Entity("ResearchHub.Models.Variable", b =>
                {
                    b.Navigation("Resultados");
                });
#pragma warning restore 612, 618
        }
    }
}
